apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-service-claim
  namespace: staging
  labels:
    app: castservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
