apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-service-claim0
  namespace: dev
  labels:
    app: cast-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
