apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cast-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.services.castservice.image.repository }}:{{ .Values.services.castservice.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.castservice.service.port }}
          env:
            {{- range .Values.services.castservice.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
          volumeMounts:
            {{- range .Values.services.castservice.volumeMounts }}
            - name: "{{ .name }}"
              mountPath: "{{ .mountPath }}"
            {{- end }}
      volumes:
        {{- range .Values.services.castservice.volumes }}
        - name: "{{ .name }}"
          persistentVolumeClaim:
            claimName: "{{ .persistentVolumeClaim.claimName }}"
        {{- end }}
