apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castserviceclaim0
  namespace: dev
  labels:
    app: castservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
