apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-service-claim
  namespace: prod
  labels:
    app: castservice
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
