apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.services.castservice.persistentVolumeClaim.name }}
  labels:
    app: castservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.castservice.persistentVolumeClaim.storage }}
