apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-service-claim0
  namespace: {{ .Namespace }}
  labels:
    app: castservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
