apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-service-claim
  namespace: qa
  labels:
    app: movieservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
