apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.services.movieservice.persistentVolumeClaim.name }}
  labels:
    app: movieservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.movieservice.persistentVolumeClaim.storage }}
