apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movieserviceclaim0
  namespace: dev
  labels:
    app: movieservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
