apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-service-claim0
  namespace: dev
  labels:
    app: movie-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
