apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-service-claim
  namespace: dev
  labels:
    app: movieservice
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
