apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-service-claim0
  namespace: {{ .Namespace }}
  labels:
    app: movieservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
