apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dev
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-dev
  hostPath:
    path: /mnt/disks/dev
  volumeMode: Filesystem
