apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prod
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-prod
  hostPath:
    path: /mnt/disks/prod
  volumeMode: Filesystem
