apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qa
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-qa
  hostPath:
    path: /mnt/disks/qa
  volumeMode: Filesystem
