apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-staging
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-staging
  hostPath:
    path: /mnt/disks/staging
  volumeMode: Filesystem
