apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-prod
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: prod
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
