apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "your-chart-name.fullname" . }}
  labels:
    app: {{ include "your-chart-name.name" . }}
    chart: {{ include "your-chart-name.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "your-chart-name.fullname" . }}
                port:
                  number: 80
