# Général
replicaCount: 1

image:
  repository: ameliendevops/jenkinsapi
  pullPolicy: IfNotPresent
  tag: ""  # Vérifiez cette valeur, une valeur vide peut poser des problèmes

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# Services spécifiques
services:
  cast-service:
    image:
      repository: ameliendevops/jenkinsapi
      tag: "latest"
    service:
      type: NodePort
      port: 8000
    volumeMounts:
      - name: cast-service-claim0
        mountPath: /app/
    volumes:
      - name: cast-service-claim0
        persistentVolumeClaim:
          claimName: cast-service-claim0
    env:
      - name: DATABASE_URI
        value: "postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev"  # Ajout des guillemets

  movie-service:
    image:
      repository: ameliendevops/jenkinsapi
      tag: "latest"
    service:
      type: NodePort
      port: 8000
    volumeMounts:
      - name: movie-service-claim0
        mountPath: /app/
    volumes:
      - name: movie-service-claim0
        persistentVolumeClaim:
          claimName: movie-service-claim0
    env:
      - name: CAST_SERVICE_HOST_URL
        value: "http://cast-service:8000/api/v1/casts/"
      - name: DATABASE_URI
        value: "postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev"  # Ajout des guillemets

# Autres configurations
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
